version: '3.8'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.95.0
    ports:
      - 4317:4317
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
