version: '3.8'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.95.0
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 4317:4317
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - 8080:8080
    environment:
      - OTEL_SERVICE_NAME=webapp
      - OTEL_RESOURCE_ATTRIBUTES=service.name=webapp
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector:4317"
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - OTEL_SERVICE_NAME=client
      - OTEL_RESOURCE_ATTRIBUTES=service.name=client
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector:4317"
      - WEBAPP_ENDPOINT="http://webapp:8080"