receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  debug:
    verbosity: detailed
service:
  telemetry:
    logs:
      encoding: json
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]