receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: otel-collector:4317
exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
service:
  telemetry:
    logs:
      encoding: json
  pipelines:
    traces:
      receivers: [otlp/notls]
      exporters: [debug, otlp]