apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-otel
  template:
    metadata:
      labels:
        app: client-otel
    spec:
      containers:
      - name: client-otel
        image: ghcr.io/p404/python-otel-example/client:latest
        env:
        - name: OTEL_SERVICE_NAME
          value: client-otel
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=client-otel
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://observe-traces.observe.svc.cluster.local:4317"
        - name: WEBAPP_ENDPOINT
          value: "http://webapp-otel:8080"
        - name: TIME_TO_WAIT
          value: "10"
