apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-otel
  template:
    metadata:
      labels:
        app: webapp-otel
    spec:
      containers:
      - name: webapp-otel
        image: ghcr.io/p404/python-otel-example/webapp:latest
        env:
        - name: OTEL_SERVICE_NAME
          value: webapp-otel
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=webapp-otel
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-otel
spec:
  selector:
    app: webapp-otel
  ports:
  - port: 8080
    targetPort: 8080
