apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/p404/python-otel-example/webapp:latest
        env:
        - name: OTEL_SERVICE_NAME
          value: webapp
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=webapp
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://observe-traces.observe.svc.cluster.local:4317"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - port: 8080
    targetPort: 8080
