name: Build and Push to GHCR

on:
  push:
    branches:
      - main 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Client Docker Image
        run: |
          docker build -f Dockerfile.client -t ghcr.io/${{ github.repository }}/client:latest .
          docker push ghcr.io/${{ github.repository }}/client:latest 

      - name: Build and Push Server Docker Image
        run: |
          docker build -f Dockerfile.webapp -t ghcr.io/${{ github.repository }}/webapp:latest . 
          docker push ghcr.io/${{ github.repository }}/webapp:latest
